package ch.heigvd.iict.and.rest.models

data class ServerContact(
    var id: Long? = null,
    var name: String,
    var firstname: String?,
    var birthday: String?,
    var email: String?,
    var address: String?,
    var zip: String?,
    var city: String?,
    var type: PhoneType?,
    var phoneNumber: String?
) {
    companion object {
        fun toServerContact(contact: Contact): ServerContact {
            return ServerContact(
                id = contact.remote_id,
                name = contact.name,
                firstname = contact.firstname,
                birthday = contact.birthday,
                email = contact.email,
                address = contact.address,
                zip = contact.zip,
                city = contact.city,
                type = contact.type,
                phoneNumber = contact.phoneNumber
            )
        }

        fun toContact(serverContact: ServerContact): Contact {
            return Contact(
                id = null, // Local id is generated by Room
                remote_id = serverContact.id,
                name = serverContact.name,
                firstname = serverContact.firstname,
                birthday = serverContact.birthday,
                email = serverContact.email,
                address = serverContact.address,
                zip = serverContact.zip,
                city = serverContact.city,
                type = serverContact.type,
                phoneNumber = serverContact.phoneNumber,
                status = Status.OK
            )
        }
    }
}
